### ISSUE TITLE
Head's Up: Crates.io Version has infinite loop, fixed here

### ISSUE THREAD

**Issue by afteralec** [robertwayne/nectar#8]
Yo! Thanks for the work on this. Just wanted to give you a heads up that it seems like there's an infinite loop in the published version of this package.

For example, using the published version on crates.io and connecting via Mudlet, Mudlet is weird and sends the GMCP byte as the first byte instead of IAC. Under these conditions (I think an unmatched byte? It's hard to tell without seeing the source of the crates.io version) the stream is never emptied and hangs on re-processing that same message.

I pulled the current version of this repo in to see if I could debug it and this behavior isn't present there.

Is this still actively being developed? If so, would you be willing to publish the current state as v0.2.0 or whichever semver this represents?

**Comment by robertwayne** [comment]
Hey, sorry about that! I wasn't getting notifications for this repo for some reason. I know this is a bit old, but I'm going to release the latest main branch, as it did fix a few issues.

Thanks for reporting this, and sorry I didn't notice sooner!

The latest branch is published to crates.io now - any new bugs can be opened in a new issue!

**Comment by afteralec** [comment]
Lovely, thanks for that!
